  - name: install apache and php for Ubuntu & Debian servers
    tags: apache, apache2, Ubuntu, gagan
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu" or ansible_nodename == "raspberrypi"

  - name: install apache and php for CentOS servers
    tags: apache, Centos, httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
