- name: install apache and php for Ubuntu & Debian servers
  tags: apache, httpd, php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name  }}" 
    state: latest

- name: start and enable apache service
  tags: apache, httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes


- name: change email address for webmaster@localhost (jetson & raspberry)
  tags: apache, ubuntu, debian, smbd
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin roland@localhost
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  register: smbd

- name: restart apache2
  tags: apache, httpd
  service:
    name: "{{ apache_service }}"
    state: restarted
  when: smbd.changed

- name: copy default html file for site
  tags: apache, apache2, httpd
  copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
